### ISSUE TITLE
Root access needed?

### ISSUE THREAD

**Issue by myth01** [ARM-software/android-nn-driver#2]
Hi @MatthewARM ,

Is root access needed to integrate Android NN driver?
Does Android O 8.1 device with ARM processor (say Huawei P20) come with Android NN driver pre-installed?

Thanks!

**Comment by MatthewARM** [comment]
Hi @myth01, integrating the driver would usually be done by your phone manufacturer. You would certainly need root access to write the driver to the system partition, and to create Android Init rules for it.

During development of the driver software we are using development boards such as Hikey 960 https://www.96boards.org/product/hikey960/ and rooted development phones so that we are in complete control of the Android image on the device.

I don't know whether it would be possible to retrofit the driver on to a retail phone.

I don't know whether the Huawei P20 using O 8.1 has this driver, that would be a question for Huawei. In general it is a decision made by the manufacturer what software they include from various sources when making the Android image for a device.

I hope that helps,

Matthew
