### ISSUE TITLE
How we measure memory needed when armnn processing a model?

### ISSUE THREAD

**Issue by uikilin100** [ARM-software/android-nn-driver#8]
How we measure memory needed when armnn processing a model?
According to model' batch number, input tensor or number of layers?

**Comment by MatthewARM** [comment]
Hi @uikilin100 usually the size of the model itself is the best indicator. The amount of working space needed by tensors is usually a lot less than the data required by all the trained parameters.

**Comment by uikilin100** [comment]
Hi @MatteoArm So if I have a model with size 10M, the memory android-nn-driver needed will be 1 * model size, 2 * model size or other proportion of model size?

**Comment by MatthewARM** [comment]
Hi @uikilin100 It'll be 1 * model size + working set size + overhead.

In the test cases I've run, the model size is the biggest (can be lots of megabytes) and the working set size is the smallest (generally the size of the biggest intermediate tensor in your net).

The working set size is affected by the Memory Manager for the backend you are using. The NEON and OpenCL backends use Compute Library which provides a pretty efficient memory manager. The Reference backend doesn't optimise memory at all so will produce big working sets.

The OpenCL backend has the biggest overhead due to compiled OpenCL kernels. I've not seen this exceed a few MB even for models with hundreds of layers.

At the end of the day, you just have to run your model and see, as model complexity affects the results.

**Comment by uikilin100** [comment]
Hi @MatthewARM Thanks for the help
I know the best way to know the memory usage is just run the model.
But it's better when we design model, we know how many memory it need in device.
Thanks for the help.
I will close the issue
